server:
  port: 9003
  servlet: ##servlet默认超时时间30分钟
    session:
      timeout: 30m
    context-path: /

spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://50.28.131.50:3306/usmsc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: zxm10
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
    hbase:
      driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
      jdbc-url: jdbc:phoenix:face.dct-unis.com:2181:/hbase
      type: com.alibaba.druid.pool.DruidDataSource
      data-username: ""
      data-password: ""
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  session:
    store-type: none

#mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
#elasticSearchClient
es:
  username: ""
  password: ""
  host: 50.28.131.32
  port: 9200
  clusterName: face.dct-znv.com
#海康SDK
hksdk:
  # false不支持海康脸谱算法 true支持海康脸谱算法
  is-switch: false
  base-url: 10.45.157.59
  app-key: '24606272'
  app-secret: 'S2K5ChipGIr6elg2RPbC'
chongqing:
  eds-url: http://50.1.64.130:10002/pingaoEds
  image-url: http://50.1.64.130:10002/getImage
  max-minute-flow: 10
  max-day-flow: 1000
bigdata:
  hdfs-url: hdfs://face.dct-unis.com:8020/user/fss/V120
###缓冲服务地址配置
mbus:
  ipp:
    - 50.28.131.59:9008
    - 50.28.131.58:9008
    - 50.28.131.57:9008
    - 50.28.131.56:9008
    - 50.28.131.55:9008
    - 50.28.131.54:9008
    - 50.28.131.53:9008
    - 50.28.131.52:9008
fdfs:
  trackers:
    - 10.45.157.59:22122
####管理服务相关配置
ms:
  image-store-type: 3
#人脸特征值
#24201#2060
####商汤服务分析引擎配置
sensetime:
  static-ai-units:
    - 50.28.131.70:9001
  dynamic-ai-units:
    - 50.28.131.70:80
  feature:
    srcPoints: {-1.0f,0.4f, 0.42f, 0.44f, 0.48f, 0.53f, 0.58f, 1.0f}
    dstPoints: {0.0f, 0.4f, 0.5f, 0.6f, 0.7f, 0.85f, 0.95f, 1.0f}
person:
  person-id-length: 16
conf:
  ##配置defaultUserId后，所有接口不登录
  defaultUserId: "11000000000"

#pagehelper.
pagehelper:
  autoDialect: true
  closeConn: true
  offset-as-page-num: false


