spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://10.45.157.117:3306/usmsc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: zxm10
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
    hbase:
      driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
      jdbc-url: jdbc:phoenix:lv116.dct-znv.com:2181:/hbase
      type: com.alibaba.druid.pool.DruidDataSource
      data-username: ""
      data-password: ""

#mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

#elasticSearchClient
es:
  username: ""
  password: ""
  host: 10.45.157.104
  port: 9200

#海康SDK
hksdk:
  # false不支持海康脸谱算法 true支持海康脸谱算法
  switch: false
  baseUrl: 10.45.157.59
  appKey: '24606272'
  appSecret: 'S2K5ChipGIr6elg2RPbC'

