package com.znv.fssrqs.entity.mysql;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.precinct_id
     *
     * @mbggenerated
     */
    private String precinctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.usergroup_id
     *
     * @mbggenerated
     */
    private String usergroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.department_id
     *
     * @mbggenerated
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.user_pwd
     *
     * @mbggenerated
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.employee_id
     *
     * @mbggenerated
     */
    private String employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.true_name
     *
     * @mbggenerated
     */
    private String trueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.mobile_telephone
     *
     * @mbggenerated
     */
    private String mobileTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.e_mail
     *
     * @mbggenerated
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.user_state
     *
     * @mbggenerated
     */
    private Integer userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.admin_user
     *
     * @mbggenerated
     */
    private String adminUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.user_sex
     *
     * @mbggenerated
     */
    private Integer userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.user_level
     *
     * @mbggenerated
     */
    private Integer userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.login_client_type
     *
     * @mbggenerated
     */
    private Integer loginClientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.dtPwUpdateTime
     *
     * @mbggenerated
     */
    private Date dtpwupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.iValidTime
     *
     * @mbggenerated
     */
    private Integer ivalidtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.user_index
     *
     * @mbggenerated
     */
    private Long userIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.dept_id
     *
     * @mbggenerated
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.flowrole_id
     *
     * @mbggenerated
     */
    private Integer flowroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.system_flag
     *
     * @mbggenerated
     */
    private Integer systemFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.is_show
     *
     * @mbggenerated
     */
    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cfg_user.user_img
     *
     * @mbggenerated
     */
    private byte[] userImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.user_id
     *
     * @return the value of t_cfg_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.user_id
     *
     * @param userId the value for t_cfg_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.precinct_id
     *
     * @return the value of t_cfg_user.precinct_id
     *
     * @mbggenerated
     */
    public String getPrecinctId() {
        return precinctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.precinct_id
     *
     * @param precinctId the value for t_cfg_user.precinct_id
     *
     * @mbggenerated
     */
    public void setPrecinctId(String precinctId) {
        this.precinctId = precinctId == null ? null : precinctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.role_id
     *
     * @return the value of t_cfg_user.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.role_id
     *
     * @param roleId the value for t_cfg_user.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.usergroup_id
     *
     * @return the value of t_cfg_user.usergroup_id
     *
     * @mbggenerated
     */
    public String getUsergroupId() {
        return usergroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.usergroup_id
     *
     * @param usergroupId the value for t_cfg_user.usergroup_id
     *
     * @mbggenerated
     */
    public void setUsergroupId(String usergroupId) {
        this.usergroupId = usergroupId == null ? null : usergroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.department_id
     *
     * @return the value of t_cfg_user.department_id
     *
     * @mbggenerated
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.department_id
     *
     * @param departmentId the value for t_cfg_user.department_id
     *
     * @mbggenerated
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.user_name
     *
     * @return the value of t_cfg_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.user_name
     *
     * @param userName the value for t_cfg_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.user_type
     *
     * @return the value of t_cfg_user.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.user_type
     *
     * @param userType the value for t_cfg_user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.user_pwd
     *
     * @return the value of t_cfg_user.user_pwd
     *
     * @mbggenerated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.user_pwd
     *
     * @param userPwd the value for t_cfg_user.user_pwd
     *
     * @mbggenerated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.employee_id
     *
     * @return the value of t_cfg_user.employee_id
     *
     * @mbggenerated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.employee_id
     *
     * @param employeeId the value for t_cfg_user.employee_id
     *
     * @mbggenerated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.true_name
     *
     * @return the value of t_cfg_user.true_name
     *
     * @mbggenerated
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.true_name
     *
     * @param trueName the value for t_cfg_user.true_name
     *
     * @mbggenerated
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName == null ? null : trueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.mobile_telephone
     *
     * @return the value of t_cfg_user.mobile_telephone
     *
     * @mbggenerated
     */
    public String getMobileTelephone() {
        return mobileTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.mobile_telephone
     *
     * @param mobileTelephone the value for t_cfg_user.mobile_telephone
     *
     * @mbggenerated
     */
    public void setMobileTelephone(String mobileTelephone) {
        this.mobileTelephone = mobileTelephone == null ? null : mobileTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.e_mail
     *
     * @return the value of t_cfg_user.e_mail
     *
     * @mbggenerated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.e_mail
     *
     * @param eMail the value for t_cfg_user.e_mail
     *
     * @mbggenerated
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.telephone
     *
     * @return the value of t_cfg_user.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.telephone
     *
     * @param telephone the value for t_cfg_user.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.address
     *
     * @return the value of t_cfg_user.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.address
     *
     * @param address the value for t_cfg_user.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.user_state
     *
     * @return the value of t_cfg_user.user_state
     *
     * @mbggenerated
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.user_state
     *
     * @param userState the value for t_cfg_user.user_state
     *
     * @mbggenerated
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.updatetime
     *
     * @return the value of t_cfg_user.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.updatetime
     *
     * @param updatetime the value for t_cfg_user.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.description
     *
     * @return the value of t_cfg_user.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.description
     *
     * @param description the value for t_cfg_user.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.admin_user
     *
     * @return the value of t_cfg_user.admin_user
     *
     * @mbggenerated
     */
    public String getAdminUser() {
        return adminUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.admin_user
     *
     * @param adminUser the value for t_cfg_user.admin_user
     *
     * @mbggenerated
     */
    public void setAdminUser(String adminUser) {
        this.adminUser = adminUser == null ? null : adminUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.fax
     *
     * @return the value of t_cfg_user.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.fax
     *
     * @param fax the value for t_cfg_user.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.user_sex
     *
     * @return the value of t_cfg_user.user_sex
     *
     * @mbggenerated
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.user_sex
     *
     * @param userSex the value for t_cfg_user.user_sex
     *
     * @mbggenerated
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.user_level
     *
     * @return the value of t_cfg_user.user_level
     *
     * @mbggenerated
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.user_level
     *
     * @param userLevel the value for t_cfg_user.user_level
     *
     * @mbggenerated
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.login_client_type
     *
     * @return the value of t_cfg_user.login_client_type
     *
     * @mbggenerated
     */
    public Integer getLoginClientType() {
        return loginClientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.login_client_type
     *
     * @param loginClientType the value for t_cfg_user.login_client_type
     *
     * @mbggenerated
     */
    public void setLoginClientType(Integer loginClientType) {
        this.loginClientType = loginClientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.dtPwUpdateTime
     *
     * @return the value of t_cfg_user.dtPwUpdateTime
     *
     * @mbggenerated
     */
    public Date getDtpwupdatetime() {
        return dtpwupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.dtPwUpdateTime
     *
     * @param dtpwupdatetime the value for t_cfg_user.dtPwUpdateTime
     *
     * @mbggenerated
     */
    public void setDtpwupdatetime(Date dtpwupdatetime) {
        this.dtpwupdatetime = dtpwupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.iValidTime
     *
     * @return the value of t_cfg_user.iValidTime
     *
     * @mbggenerated
     */
    public Integer getIvalidtime() {
        return ivalidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.iValidTime
     *
     * @param ivalidtime the value for t_cfg_user.iValidTime
     *
     * @mbggenerated
     */
    public void setIvalidtime(Integer ivalidtime) {
        this.ivalidtime = ivalidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.user_index
     *
     * @return the value of t_cfg_user.user_index
     *
     * @mbggenerated
     */
    public Long getUserIndex() {
        return userIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.user_index
     *
     * @param userIndex the value for t_cfg_user.user_index
     *
     * @mbggenerated
     */
    public void setUserIndex(Long userIndex) {
        this.userIndex = userIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.dept_id
     *
     * @return the value of t_cfg_user.dept_id
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.dept_id
     *
     * @param deptId the value for t_cfg_user.dept_id
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.flowrole_id
     *
     * @return the value of t_cfg_user.flowrole_id
     *
     * @mbggenerated
     */
    public Integer getFlowroleId() {
        return flowroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.flowrole_id
     *
     * @param flowroleId the value for t_cfg_user.flowrole_id
     *
     * @mbggenerated
     */
    public void setFlowroleId(Integer flowroleId) {
        this.flowroleId = flowroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.system_flag
     *
     * @return the value of t_cfg_user.system_flag
     *
     * @mbggenerated
     */
    public Integer getSystemFlag() {
        return systemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.system_flag
     *
     * @param systemFlag the value for t_cfg_user.system_flag
     *
     * @mbggenerated
     */
    public void setSystemFlag(Integer systemFlag) {
        this.systemFlag = systemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.is_show
     *
     * @return the value of t_cfg_user.is_show
     *
     * @mbggenerated
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.is_show
     *
     * @param isShow the value for t_cfg_user.is_show
     *
     * @mbggenerated
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.create_time
     *
     * @return the value of t_cfg_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.create_time
     *
     * @param createTime the value for t_cfg_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cfg_user.user_img
     *
     * @return the value of t_cfg_user.user_img
     *
     * @mbggenerated
     */
    public byte[] getUserImg() {
        return userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cfg_user.user_img
     *
     * @param userImg the value for t_cfg_user.user_img
     *
     * @mbggenerated
     */
    public void setUserImg(byte[] userImg) {
        this.userImg = userImg;
    }
}